version: '2.0'

services:
 permission_request_cron:
  build:
   context: /glb/home/s_tlstcs/permission_request_app/dev/docker-cron
   dockerfile: Dockerfile
  container_name: permission_request_cron_dev
  image: permission_request_cron_dev
  restart: always
  networks:
   permission_request_network_cron_dev:
    ipv4_address: 172.29.0.2
  volumes:
   - /glb/home/s_tlstcs/permission_request_app/dev/bin:/opt/permission_request/bin
   - /glb/home/s_tlstcs/:/glb/home/s_tlstcs/

networks:
 permission_request_network_cron_dev:
  driver: bridge
  ipam:
   config:
    - subnet: 172.29.0.0/16
      ip_range: 172.29.0.0/24


